### ISSUE TITLE
Queue bind problems results in connection leakage

### ISSUE THREAD

**Issue by magnusbaeck** [logstash-plugins/logstash-mixin-rabbitmq_connection#4]
If the rabbitmq input plugin is configured to bind to an exchange that doesn't exist an AMQP connection will leak every ten seconds. For example, the Logstash configuration

```
input {
  rabbitmq {
    host => ["rabbitmq.example.com"]
    durable => true
    exchange => "non-existent-exchange"
    queue => "myqueue"
    key => "#"
    user => "joe"
    password => "secret"
    type => "anytype"
  }
}
```

will result in the following message repeating itself in the Logstash log:

```
{:timestamp=>"2015-10-07T17:27:45.036000+0200", :message=>"RabbitMQ connection error: NOT_FOUND - no exchange 'non-existent-exchange' in vhost '/'. Will reconnect in 10 seconds...", :level=>:error}
```

Each time this happens we leak an AMQP connection. I ended up with over 8000 connections in my RabbitMQ instance and roughly the same number of log messages like the one above.

I'm not sure if the problem is the logstash-mixin-rabbitmq_connection library or march_hare or the rabbitmq input plugin itself, but I suspect RabbitMQConnection.connect is called multiple times without either closing the existing connection first or reusing the existing connection.

**Comment by CVTJNII** [comment]
I'm seeing this with a locked queue message

```
{:timestamp=>"2016-07-11T15:19:40.501000+0000", :message=>"RabbitMQ connection error: RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'logstash' in vhost '/'. Will reconnect in 10 seconds...", :level=>:error}
```

I'm assuming this has been fixed in newer versions as I'm seeing this on logstash 1.3.2 which is quite old, but I haven't seen this on logstash 2.3 which we're migrating to.

**Comment by andrewvc** [comment]
@CVTJNII this was almost certainly fixed by some major refactorings of connection code. I'm going to close this issue, but if you experience this on a newer Logstash please reopen the issue.
