### ISSUE TITLE
SSL Certificate verificiation result is ignored

### ISSUE THREAD

**Issue by sigsegv11** [logstash-plugins/logstash-mixin-rabbitmq_connection#44]
When setting the ssl_certificate_password/ssl_certificate_path for the rabbitmq plugin logstash keeps trusting certificates that can not be verified by the certificate provided in ssl_certificate_path.
This also higlighter by the continuous output of:

> [WARN ][com.rabbitmq.client.NullTrustManager] This trust manager trusts every certificate, effectively disabling peer verification. This is convenient for local development but prone to man-in-the-middle attacks. Please see http://www.rabbitmq.com/ssl.html#validating-cerficates to learn more about peer certificate validation.

Diving a bit deeper into the code the issues seems to come from using march_hare without setting a custom truststore. ( see [line 101](https://github.com/ruby-amqp/march_hare/blob/master/lib/march_hare/session.rb)). Because of this we fall back with the default "com.rabbitmq.client.NullTrustManager". It does trust[ everything](https://www.rabbitmq.com/releases/rabbitmq-java-client/v3.2.4/rabbitmq-java-client-javadoc-3.2.4/com/rabbitmq/client/NullTrustManager.html) by default without bothering checking certificates. As a result the ssl_certificate options simply doesn't work.

**Comment by andrewvc** [comment]
Ah, good find! Will take a look at this.

**Comment by andrewvc** [comment]
I've opened an issue here: https://github.com/ruby-amqp/march_hare/issues/127

**Comment by michaelklishin** [comment]
What March Hare doesn't do is allow for the user to pass a custom trust store manager. Sounds like a trivial fix, feel free to look into a PR.

I'm not aware of an easy way of setting up key and trust stores from Ruby, so passing in a custom trust store manager is what should be done for now. What's the best way forLogstash to decide what implementation to use and how to set it up is a question I'm not really qualified to answer. Again, it comes down to a verbose Java API for that.

**Comment by jakelandis** [comment]
I have a PR https://github.com/ruby-amqp/march_hare/pull/128 to fix this upstream in the connection library we use.
